/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CyclesIndexRouteImport } from './routes/cycles.index'
import { Route as CyclesCycleIdRouteImport } from './routes/cycles.$cycleId'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as PortalInvestorRouteImport } from './routes/portal.investor'
import { Route as PortalOperatorRouteImport } from './routes/portal.operator'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api.public.paystack-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesIndexRoute = CyclesIndexRouteImport.update({
  id: '/cycles/',
  path: '/cycles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesCycleIdRoute = CyclesCycleIdRouteImport.update({
  id: '/cycles/$cycleId',
  path: '/cycles/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvestorRoute = PortalInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOperatorRoute = PortalOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/signin': typeof SigninRoute
  '/api/health': typeof ApiHealthRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/investor': typeof PortalInvestorRoute
  '/portal/operator': typeof PortalOperatorRoute
  '/cycles/': typeof CyclesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/health': typeof ApiHealthRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/investor': typeof PortalInvestorRoute
  '/portal/operator': typeof PortalOperatorRoute
  '/cycles': typeof CyclesIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/signin': typeof SigninRoute
  '/api/health': typeof ApiHealthRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/investor': typeof PortalInvestorRoute
  '/portal/operator': typeof PortalOperatorRoute
  '/cycles/': typeof CyclesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/signin'
    | '/api/health'
    | '/cycles/$cycleId'
    | '/legal/$doc'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/operator'
    | '/cycles/'
    | '/portal/'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/api/health'
    | '/cycles/$cycleId'
    | '/legal/$doc'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/operator'
    | '/cycles'
    | '/portal'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/signin'
    | '/api/health'
    | '/cycles/$cycleId'
    | '/legal/$doc'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/operator'
    | '/cycles/'
    | '/portal/'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CyclesCycleIdRoute: typeof CyclesCycleIdRoute
  LegalDocRoute: typeof LegalDocRoute
  CyclesIndexRoute: typeof CyclesIndexRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/': {
      id: '/cycles/'
      path: '/cycles'
      fullPath: '/cycles/'
      preLoaderRoute: typeof CyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/$cycleId': {
      id: '/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/cycles/$cycleId'
      preLoaderRoute: typeof CyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/investor': {
      id: '/portal/investor'
      path: '/investor'
      fullPath: '/portal/investor'
      preLoaderRoute: typeof PortalInvestorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/operator': {
      id: '/portal/operator'
      path: '/operator'
      fullPath: '/portal/operator'
      preLoaderRoute: typeof PortalOperatorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalInvestorRoute: typeof PortalInvestorRoute
  PortalOperatorRoute: typeof PortalOperatorRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalInvestorRoute: PortalInvestorRoute,
  PortalOperatorRoute: PortalOperatorRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiHealthRoute: ApiHealthRoute,
  CyclesCycleIdRoute: CyclesCycleIdRoute,
  LegalDocRoute: LegalDocRoute,
  CyclesIndexRoute: CyclesIndexRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
